FROM eclipse-temurin:21-jdk
LABEL maintainer="sso-project"

# 设置时区（解决容器内时间差8小时问题）
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo "Asia/Shanghai" > /etc/timezone

# 复制认证中心构建好的 Jar 包
COPY xcx1-auth/target/xcx1-auth-1.0.0.jar /app/app.jar

# 暴露端口
EXPOSE 3004

# 启动命令（优化随机数生成器，加快启动速度）
ENTRYPOINT ["java", "-Djava.security.egd=file:/dev/./urandom", "-jar", "/app/app.jar"]
