apiVersion: apps/v1
kind: Deployment
metadata:
  name: xcx1-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xcx1-auth
  template:
    metadata:
      labels:
        app: xcx1-auth
    spec:
      containers:
        - name: xcx1-auth
          image: xcx1-auth:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3004
---
apiVersion: v1
kind: Service
metadata:
  name: xcx1-auth-service
spec:
  selector:
    app: xcx1-auth
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3004
  type: ClusterIP