apiVersion: apps/v1
kind: Deployment
metadata:
  name: system-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: system-a
  template:
    metadata:
      labels:
        app: system-a
    spec:
      containers:
        - name: system-a
          image: system-a:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3005
---
apiVersion: v1
kind: Service
metadata:
  name: system-a-service
spec:
  selector:
    app: system-a
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3005
  type: ClusterIP