apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: xcx1-gateway-ingress
  annotations:
    # Traefik 特定配置
    traefik.ingress.kubernetes.io/router.entrypoints: web
    kubernetes.io/ingress.class: traefik
spec:
  rules:
#    - host: localhost
#      http:  把 host: localhost这一行删除了。这样配置后，Ingress（网关）就不再检查“口令”（域名）
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: xcx1-gateway-service
                port:
                  number: 80
    # 也支持通过 IP 访问
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: xcx1-gateway-service
                port:
                  number: 80
